In [31]:
import numpy as np


def create_1d_array_zeros(size: int = 1) -> np.array:
    return np.zeros(size)


In [32]:
create_1d_array_zeros(5)


array([0., 0., 0., 0., 0.])

In [33]:
#FONTOS!!!

# CSAK OTT LEHET HASZNÁLNI FOR LOOP-OT AHOL A FELADAT KÜLÖN KÉRI!
# [1,2,3,4] --> ezek az értékek np.array-ek. Ahol listát kérek paraméterként ott külön ki fogom emelni!
# Ha végeztél a feladatokkal, akkor notebook-ot alakítsd át .py.
# A FÁJLBAN CSAK A FÜGGVÉNYEK LEGYENEK! (KOMMENTEK MARADHATNAK)

In [34]:
#Készíts egy függvényt ami létre hoz egy nullákkal teli numpy array-t.
#Paraméterei: mérete (tuple-ként), default mérete pedig legyen egy (2,2)
#Be: (2,2)
#Ki: [[0,0],[0,0]]
#create_array()

In [35]:
def create_array(shape: tuple = (2, 2)) -> np.array:
    return np.zeros(shape, dtype=int).tolist()


create_array((3, 4))


[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]

In [36]:
#Készíts egy függvényt ami a paraméterként kapott array-t főátlóját feltölti egyesekkel
#Be: [[1,2],[3,4]]
#Ki: [[1,2],[3,1]]
#set_one()

In [37]:
def set_one(arr: np.array) -> np.array:
    np.fill_diagonal(arr, 1)
    return arr


set_one(np.array([[1, 2], [3, 4]]))


array([[1, 2],
       [3, 1]])

In [38]:
# Készíts egy függvényt ami transzponálja a paraméterül kapott mártix-ot:
# Be: [[1, 2], [3, 4]]
# Ki: [[1, 2], [3, 4]]
# do_transpose()

In [39]:
def do_transpose(matrix: np.array) -> np.array:
    return np.transpose(matrix).tolist()


do_transpose(np.array([[1, 2], [3, 4]]))


[[1, 3], [2, 4]]

In [40]:
# Készíts egy olyan függvényt ami az array-ben lévő értékeket N tizenedjegyik kerekíti, ha nincs megadva ez a paraméter, akkor legyen az alapértelmezett a kettő 
# Be: [0.1223, 0.1675], 2
# Ki: [0.12, 0.17]
# round_array()

In [41]:
def round_array(arr: np.array, n: int):
    return np.round(arr, n)


round_array([0.1223, 0.1675], 2)


array([0.12, 0.17])

In [42]:
# Készíts egy olyan függvényt, ami a bementként kapott 0 és 1 ből álló tömben a 0 - False-ra, az 1 True-ra cserélni
# Be: [[1, 0, 0], [1, 1, 1],[0, 0, 0]]
# Ki: [[ True False False], [ True  True  True], [False False False]]
# bool_array()

In [43]:
def bool_array(arr: np.array) -> np.array:
    return np.array(arr, dtype=bool)


bool_array([[1, 0, 0], [1, 1, 1], [0, 0, 0]])


array([[ True, False, False],
       [ True,  True,  True],
       [False, False, False]])

In [44]:
# Készíts egy olyan függvényt, ami a bementként kapott 0 és 1 ből álló tömben a 1 - False-ra az 0 True-ra cserélni
# Be: [[1, 0, 0], [1, 1, 1],[0, 0, 0]]
# Ki: [[ True False False], [ True  True  True], [False False False]]
# invert_bool_array()

In [45]:
def invert_bool_array(arr: np.array) -> np.array:
    return np.where(arr, False, True)


invert_bool_array([[1, 0, 0], [1, 1, 1], [0, 0, 0]])


array([[False,  True,  True],
       [False, False, False],
       [ True,  True,  True]])

In [46]:
# Készíts egy olyan függvényt ami a paraméterként kapott array-t kilapítja
# Be: [[1,2], [3,4]]
# Ki: [1,2,3,4]
# flatten()


In [47]:
def flatten(input_arr: np.array) -> np.array:
    return np.array(input_arr).flatten().tolist()


flatten([[1, 2], [3, 4]])


[1, 2, 3, 4]