In [40]:
import numpy as np

In [41]:
#FONTOS!!!

# CSAK OTT LEHET HASZNÁLNI FOR LOOP-OT AHOL A FELADAT KÜLÖN KÉRI!
# [1,2,3,4] --> ezek az értékek np.array-ek. Ahol listát kérek paraméterként ott külön ki fogom emelni!
# Ha végeztél a feladatokkal, akkor notebook-ot alakítsd át .py.
# A FÁJLBAN CSAK A FÜGGVÉNYEK LEGYENEK! (KOMMENTEK MARADHATNAK)

In [42]:
# Írj egy olyan fügvényt, ami megfordítja egy 2d array oszlopait. Bemenetként egy array-t vár.
# Be: [[1,2],[3,4]]
# Ki: [[2,1],[4,3]]
# column_swap()

In [43]:
def column_swap(arr: np.array) -> np.array:
    return np.flip(arr, axis=1)


column_swap([[1, 2], [3, 4]])


array([[2, 1],
       [4, 3]])

In [44]:
# Készíts egy olyan függvényt ami összehasonlít két array-t és adjon vissza egy array-ben, hogy hol egyenlőek 
# Pl Be: [7,8,9], [9,8,7] 
# Ki: [1]
# compare_two_array()
# egyenlő elemszámúakra kell csak hogy működjön

In [70]:
def compare_two_array(a: np.array, b: np.array) -> np.array:
    return np.where(a == b)[0]


compare_two_array(np.array([7, 8, 9]), np.array([9, 8, 7]))


array([1], dtype=int64)

In [46]:
# Készíts egy olyan függvényt, ami vissza adja string-ként a megadott array dimenzióit:
# Be: [[1,2,3], [4,5,6]]
# Ki: "sor: 2, oszlop: 3, melyseg: 1"
# get_array_shape()
# 3D-vel még műküdnie kell!, 

In [47]:
def get_array_shape(arr: np.array) -> str:
    shape = np.shape(arr)
    return f"sor: {shape[0]}, oszlop: {shape[1]}, melyseg: {shape[2] if len(shape) == 3 else 1}"


get_array_shape([[1, 2, 3], [4, 5, 6]])


'sor: 2, oszlop: 3, melyseg: 1'

In [48]:
# Készíts egy olyan függvényt, aminek segítségével elő tudod állítani egy neurális hálózat tanításához szükséges pred-et egy numpy array-ből. 
# Bementként add meg az array-t, illetve hogy mennyi class-od van. Kimenetként pedig adjon vissza egy 2d array-t, ahol a sorok az egyes elemek. Minden nullákkal teli legyen és csak ott álljon egyes, ahol a bementi tömb megjelöli. 
# Pl. ha 1 van a bemeneten és 4 classod van, akkor az adott sorban az array-ban a [1] helyen álljon egy 1-es, a többi helyen pedig 0.
# Be: [1, 2, 0, 3], 4
# Ki: [[0,1,0,0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 0, 1]]
# encode_Y()

In [49]:
def encode_Y(y: np.array, num_classes: np.array) -> np.array:
    encoded = np.zeros((len(y), num_classes))
    encoded[np.arange(len(y)), y] = 1
    return encoded


encode_Y([1, 2, 0, 3], 4)


array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [50]:
# A fenti feladatnak valósítsd meg a kiértékelését. Adj meg a 2d array-t és adj vissza a decodolt változatát
# Be:  [[0,1,0,0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 0, 1]]
# Ki:  [1, 2, 0, 3]
# decode_Y()

In [66]:
def decode_Y(encoded_Y: np.array) -> np.array:
    return np.nonzero(encoded_Y)[1]


decode_Y([[0, 1, 0, 0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 0, 1]])


array([1, 2, 0, 3], dtype=int64)

In [52]:
# Készíts egy olyan függvényt, ami képes kiértékelni egy neurális háló eredményét! Bemenetként egy listát és egy array-t és adja vissza azt az elemet, aminek a legnagyobb a valószínüsége(értéke) a listából.
# Be: ['alma', 'körte', 'szilva'], [0.2, 0.2, 0.6]. # Az ['alma', 'körte', 'szilva'] egy lista!
# Ki: 'szilva'
# eval_classification()

In [53]:
def eval_classification(labels: list, predictions: np.array) -> str:
    return labels[np.argmax(predictions)]


eval_classification(['alma', 'körte', 'szilva'], [0.2, 0.2, 0.6])


'szilva'

In [54]:
# Készíts egy olyan függvényt, ahol az 1D array-ben a páratlan számokat -1-re cseréli
# Be: [1,2,3,4,5,6]
# Ki: [-1,2,-1,4,-1,6]
# replace_odd_numbers()

In [55]:
def replace_odd_numbers(arr: np.array) -> np.array:
    arr[arr % 2 != 0] = -1
    return arr


replace_odd_numbers([1, 2, 3, 4, 5, 6])


array([-1,  2, -1,  4, -1,  6])

In [56]:
# Készíts egy olyan függvényt, ami egy array értékeit -1 és 1-re változtatja, attól függően, hogy az adott elem nagyobb vagy kisebb a paraméterként megadott számnál.
# Ha a szám kisebb mint a megadott érték, akkor -1, ha nagyobb vagy egyenlő, akkor pedig 1.
# Be: [1, 2, 5, 0], 2
# Ki: [-1, 1, 1, -1]
# replace_by_value()

In [57]:
def replace_by_value(arr: np.array, val: int) -> np.array:
    return np.where(arr >= val, 1, -1)


replace_by_value([1, 2, 5, 0], 2)


array([-1,  1,  1, -1])

In [58]:
# Készíts egy olyan függvényt, ami egy array értékeit összeszorozza és az eredményt visszaadja
# Be: [1,2,3,4]
# Ki: 24
# array_multi()
# Ha több dimenziós a tömb, akkor az egész tömb elemeinek szorzatával térjen vissza

In [59]:
def array_multi(arr: np.array) -> int:
    return np.prod(arr)


array_multi([1, 2, 3, 4])


24

In [60]:
# Készíts egy olyan függvényt, ami egy 2D array értékeit összeszorozza és egy olyan array-el tér vissza, aminek az elemei a soroknak a szorzata
# Be: [[1, 2], [3, 4]]
# Ki: [2, 12]
# array_multi_2d()

In [61]:
def array_multi_2d(arr: np.array) -> np.array:
    return np.prod(arr, axis=1)


array_multi_2d([[1, 2], [3, 4]])


array([ 2, 12])

In [62]:
# Készíts egy olyan függvényt, amit egy meglévő numpy array-hez készít egy bordert nullásokkal. Bementként egy array-t várjon és kimenetként egy array jelenjen meg aminek van border-je
# Be: [[1,2],[3,4]]
# Ki: [[0,0,0,0],[0,1,2,0],[0,3,4,0],[0,0,0,0]]
# add_border()


In [71]:
def add_border(arr: np.array) -> np.array:
    rows, cols = arr.shape
    new_rows, new_cols = rows + 2, cols + 2
    new_arr = np.zeros((new_rows, new_cols))
    new_arr[1:-1, 1:-1] = arr
    return new_arr


add_border([[1, 2], [3, 4]])


AttributeError: 'list' object has no attribute 'shape'

In [ ]:
# A KÖTVETKEZŐ FELADATOKHOZ NÉZZÉTEK MEG A NUMPY DATA TYPE-JÁT!

In [ ]:
# Készíts egy olyan függvényt ami két dátum között felsorolja az összes napot és ezt adja vissza egy numpy array-ben. A fgv ként str vár paraméterként 'YYYY-MM' formában.
# Be: '2023-03', '2023-04'  # mind a kettő paraméter str.
# Ki: ['2023-03-01', '2023-03-02', .. , '2023-03-31',]
# list_days()

In [72]:
def list_days(start_date: str, end_date: str) -> np.array:
    start = np.datetime64(start_date)
    end = np.datetime64(end_date)
    days = np.arange(start, end + np.timedelta64(1, 'D'),
                     np.timedelta64(1, 'D'))
    return np.array(days, dtype='datetime64[D]').astype(str)


list_days('2023-03', '2023-04')


array(['2023-03-01', '2023-03-02', '2023-03-03', '2023-03-04',
       '2023-03-05', '2023-03-06', '2023-03-07', '2023-03-08',
       '2023-03-09', '2023-03-10', '2023-03-11', '2023-03-12',
       '2023-03-13', '2023-03-14', '2023-03-15', '2023-03-16',
       '2023-03-17', '2023-03-18', '2023-03-19', '2023-03-20',
       '2023-03-21', '2023-03-22', '2023-03-23', '2023-03-24',
       '2023-03-25', '2023-03-26', '2023-03-27', '2023-03-28',
       '2023-03-29', '2023-03-30', '2023-03-31', '2023-04-01'],
      dtype='<U28')

In [ ]:
# Írj egy fügvényt ami vissza adja az aktuális dátumot az alábbi formában: YYYY-MM-DD. Térjen vissza egy 'numpy.datetime64' típussal.
# Be:
# Ki: 2017-03-24
# get_act_date()

In [73]:
def get_act_date() -> np.datetime64:
    return np.datetime64('today')


get_act_date()


numpy.datetime64('2023-03-10')

In [ ]:
# Írj egy olyan függvényt ami visszadja, hogy mennyi másodperc telt el 1970 január 01. 00:02:00 óta. Int-el térjen vissza
# Be: 
# Ki: másodpercben az idó, int-é kasztolva
# sec_from_1970()

In [81]:
def sec_from_1970():
    now = np.datetime64('now')
    delta = now - np.datetime64('1970-01-01T00:02:00')
    return int(delta / np.timedelta64(1, 's'))


sec_from_1970()


1678459766